export const filterCategories = {
  industry: {
    name: 'Отрасль',
    items: [
      'BI-отчеты',
      'Гос. заказ',
      'Энергетика',
      'Образование',
      'Финтех',
      'Образ жизни',
      'Медицина',
      'E-commerce',
      'Безопасность',
      'Развлечения',
      'Картография',
    ],
  },
  platform: {
    name: 'Платформы',
    items: ['Android', 'Chat-system', 'Telegram', 'Backend', 'Windows', 'Панель управления', 'Web', 'iOS'],
  },
  service: {
    name: 'Услуги',
    items: [
      'Релиз',
      'Сопровождение',
      'Дизайн',
      'Тестирование',
      'Разработка',
      'Предпроектная деятельность',
      'Аналитика',
      'Приемка',
    ],
  },
  language: {
    name: 'Языки',
    items: [
      'Node.JS',
      'Java',
      'Xamarin',
      'Wordpress',
      'Drupal 8, Angular',
      'ASP.NET Core, Azure',
      'MS Power BI',
      '1C-Битрикс',
      'Objective-C',
      'C#, UWP',
      'Python',
      'PHP',
      'Kotlin',
      'MODX',
      'Swift',
      'PhoneGap',
      'React',
      'Java, Kotlin',
      'Cordova',
      'C++',
    ],
  },
}
